services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

#  app:
#    build: .
#    ports:
#      - "8000:8000"
#    environment:
#      - CACHE_HOST=redis
#      - CACHE_PORT=6379
#      - CACHE_DB=0
#    depends_on:
#      redis:
#        condition: service_healthy
#    restart: unless-stopped
#
volumes:
  redis_data: